/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import BEAN.Producto;
import DAO.productoDAO;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorioesan
 */
public class SelProducto extends javax.swing.JDialog {
    DefaultTableModel dtm;
    productoDAO prodDAO;
    Producto prod;
    /**
     * Creates new form SelProducto
     */
    public SelProducto(java.awt.Frame parent, boolean modal,int mdiH,int mdiW) {
        super(parent, modal);
        int slx,sly;
        initComponents();
        slx = (mdiW/2)-(400/2);
        sly = (mdiH/2)-(300/2);
        this.setSize(400,300);
        this.setLocation(slx,sly);
        prodDAO = new productoDAO();
        dtm = (DefaultTableModel)this.tblProducto.getModel();
        llenaProducto(false,"");
    }
    public void llenaProducto(boolean swr, String cad){
        Vector<Producto> listProd = prodDAO.ListaItem(swr, cad);
        if(dtm.getRowCount()>0){
            dtm.setRowCount(0);  //Este método limpia el jtable cliente
        }
        for(int i=0;i<listProd.size();i++){
            Vector vProd = new Vector();
            vProd.add(0, listProd.get(i).getId_producto());
            vProd.add(1, listProd.get(i).getDescripcion());
            vProd.add(2, listProd.get(i).getTipo());
            vProd.add(3, listProd.get(i).getPrecio());
            vProd.add(4, listProd.get(i).getEstado());
            dtm.addRow(vProd);            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SELECCIONA PRODUCTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 210, 30);

        jLabel2.setText("Búsqueda");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 60, 14);

        txtProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdKeyReleased(evt);
            }
        });
        getContentPane().add(txtProd);
        txtProd.setBounds(80, 50, 310, 30);

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Producto", "Descripción", "Tipo", "Precio", "Estado"
            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 380, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdKeyReleased
        if(this.txtProd.getText().isEmpty()){
            llenaProducto(false, "");
        }else{
            llenaProducto(true, this.txtProd.getText());
        }
    }//GEN-LAST:event_txtProdKeyReleased

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        prod = new Producto();
        int fila;
        fila = this.tblProducto.getSelectedRow();
        prod.setId_producto(Integer.parseInt(dtm.getValueAt(fila, 0).toString()));
        prod.setDescripcion(dtm.getValueAt(fila, 1).toString());
        prod.setTipo(dtm.getValueAt(fila, 2).toString());
        prod.setPrecio(Double.parseDouble(dtm.getValueAt(fila, 3).toString()));
        prod.setEstado(Integer.parseInt(dtm.getValueAt(fila, 4).toString()));
        this.dispose();
    }//GEN-LAST:event_tblProductoMouseClicked
    public Producto devProducto(){
        return prod;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtProd;
    // End of variables declaration//GEN-END:variables
}
